### PR TITLE
Organize kubernetes object creation based on Helm order

### PR DESCRIPTION
**Pull request by bdunne**
https://github.com/kubernetes/helm/blob/29c3b5276f0290d21d43ef45ad0230e45b460b27/pkg/tiller/kind_sorter.go#L29

### CODE REVIEW

**Comment by ehelms** [comment]
Is it better to do it fully by types vs by "application" then this sorting? My original intent was to express some idea of here are the tier 1 backend systems, then tier 2 and up, along with grouping within the application the relative pieces. If this sort of organization doesn't out weigh this sorted ordering then I'm happy to take this as is.

I suppose we are striving for blast them all into Kubernetes and let the services sort it out anyway?

**Comment by carbonin** [comment]
I guess the easiest example for why I like the ordering based on kind better is that there are environment variables which are based on service names (`QPID_SERVICE_HOST`, for example). If we are ever in a situation where there is a mutual service dependency between applications then we would really want all the services created before the deployments for both applications.

**Comment by ehelms** [comment]
I think that's fair. If this were ever re-factored into roles per application, this ordering would go back to by application because we'd be letting, for example, the qpid role determine how to spin up qpid bits as a dependency of all the other applications. For now, I'll merge this as is.

**Comment by carbonin** [comment]
Yeah, so what helm does it take all of the dependent charts and order their components in the same way so they would get interleaved like this.

If we ever called just an application's main playbook to deploy then we would need to ensure the dependency ordering made sense.

**Pull request merged**
